### ISSUE TITLE
(CI/CD) - Configure unit tests to run in every pull request

### ISSUE THREAD

**Issue by ItaloRAmaral** [ItaloRAmaral/cliniccontrol#57]
## O que ? 

-  Criar uma github action (pipeline) para rodar os testes em toda PR, caso falhe, bloquear a PR

## Como ?

- Criando um arquivo em `./github/workflow/<automated_tests>.yml`
- O inicio de um trigger de pull request geralmente é assim: 
```yml
name: <pipeline name>

on: [pull_request]

  unit_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    strategy:
      matrix:
        node-version: [18]
        npm-version: [8]
        yarn-version: ['1.22.x']
        pnpm-version: [8]
...
```

## Porque ?

- Para treinar skills de lógica de pipeline
- Para treinar o uso de bash, curl, e apis externas de integração

## Pair Programming ?

- [ ] Sim
- [x] Não

## Referencias
- Usar de referencia o steps de instalação de dependencias do nosso workflow de pre-release ( a partir da linha 53 )
   - https://github.com/ItaloRAmaral/cliniccontrol/blob/main/.github/workflows/pre-release.yml

- Link de um video no youtube que possa ajudar a criar a pipeline de testes automatizados
   - https://www.youtube.com/watch?v=WW6ZUw9IExA&list=PLOQjd5dsGSxKC4K12-iLnla5E7rjJr_Ts&index=2
